### ISSUE TITLE
Initialization error

### ISSUE THREAD

**Issue by SkarletShadows** [Cozary/Issue-Tracker#25]
## Information
Forge version: 41.0.87
Minecraft: 1.19
Mod: Tinted Campfires
Version: 1.19.0-1.2.2
## Code
    -- MOD tintedcampfires --
    Details:
	    Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ParticleFactoryRegisterEvent
		    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		    at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		    at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		    at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		    at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
		    at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
		    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
		    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
    
	    Mod File: Tinted Campfires-1.19-1.2.2.jar
	    Failure message: Tinted Campfires (tintedcampfires) has failed to load correctly
		    java.lang.NoClassDefFoundError: net/minecraftforge/client/event/ParticleFactoryRegisterEvent
	    Mod Version: 1.19.0-1.2.2
	    Mod Issue URL: NOT PROVIDED
	    Exception message: java.lang.ClassNotFoundException: net.minecraftforge.client.event.ParticleFactoryRegisterEvent
    Stacktrace:
	    at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	    at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	    at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	    at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	    at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:75) ~[eventbus-6.0.0.jar%2378!/:?] {}
	    at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[eventbus-6.0.0.jar%2378!/:?] {}
	    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	    at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19-41.0.87.jar%23170!/:?] {}
	    at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19-41.0.87.jar%23169!/:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	    at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

**Comment by SkarletShadows** [comment]
The forge version was too high, I apologize!

**Comment by Cozary** [comment]
Yes, this usually happens when they release so many versions. Don't worry.
