### ISSUE TITLE
Ticking Entity crash, seems to be caused by the recent update to the Experience Battery.

### ISSUE THREAD

**Issue by Mqony** [Cozary/Issue-Tracker#63]
**Versions:** Forge 1.18.2, Nameless Trinkets 1.7.0, Curios 5.0.9.0, ExpandAbility 6.0.0

**How to Reproduce:** Die to any mob in Survival mode. A ticking entity crash will occur and the crash report will say that it was caused by the mob that you died to. The game crashes 100% of the time and there are no other mods installed on this instance aside from Nameless Trinkets, Curios, and ExpandAbility.

[crashreport.txt](https://github.com/Cozary/Issue-Tracker/files/11682283/crashreport.txt)

**Comment by MVandal80** [comment]
I have experienced the same issue.

------------------------------------
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.getCapability(net.minecraftforge.common.capabilities.Capability)" because "livingEntity" is null
	at top.theillusivec4.curios.common.CuriosHelper.getCuriosHandler(CuriosHelper.java:81) ~[curios-forge-1.19.2-5.1.4.1.jar%23419!/:1.19.2-5.1.4.1] {re:classloading}
	at top.theillusivec4.curios.common.CuriosHelper.findFirstCurio(CuriosHelper.java:135) ~[curios-forge-1.19.2-5.1.4.1.jar%23419!/:1.19.2-5.1.4.1] {re:classloading}
	at top.theillusivec4.curios.common.CuriosHelper.findFirstCurio(CuriosHelper.java:129) ~[curios-forge-1.19.2-5.1.4.1.jar%23419!/:1.19.2-5.1.4.1] {re:classloading}
	at com.cozary.nameless_trinkets.items.trinkets.ExperienceBattery.function(ExperienceBattery.java:87) ~[Nameless%20Trinkets-1.19.2-1.7.0.jar%23495!/:?] {re:classloading}
	at com.cozary.nameless_trinkets.items.trinkets.__ExperienceBattery_function_LivingExperienceDropEvent.invoke(.dynamic) ~[Nameless%20Trinkets-1.19.2-1.7.0.jar%23495!/:?] {re:classloading,pl:eventbus:B}

**Comment by Cozary** [comment]
The problem is fixed, I strongly recommend you to use v1.7.2

The file is uploaded but it will take a while to be available. ^^

The item tried to calculate the experience that the player should gain, and although it is made so that the players do not drop extra experience the game tried to detect the player's Trinket and since the player was dead there was no trinket, that caused the crash.
